const periodictabledata =
[
    {
        name: "Hidr&oacute;geno",
        atomicnumber: 1,
        symbol: "H",
        category: "Reactivo no metal",
        atomicweight: "1.008",
        atomicweightfull: "[1.00784, 1.00811]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 1,
        period: 1,
        block: "s",
        tablerow18col: 1,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Helio",
        atomicnumber: 2,
        symbol: "He",
        category: "Gas Noble",
        atomicweight: "4.0026",
        atomicweightfull: "4.002602(2)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 1,
        block: "s",
        tablerow18col: 1,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Litio",
        atomicnumber: 3,
        symbol: "Li",
        category: "Metal alcalino",
        atomicweight: "6.94",
        atomicweightfull: "[6.938, 6.997]",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 1,
        period: 2,
        block: "s",
        tablerow18col: 2,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Berilio",
        atomicnumber: 4,
        symbol: "Be",
        category: "Alcalinotérreo",
        atomicweight: "9.0122",
        atomicweightfull: "9.0121831(5)",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 2,
        period: 2,
        block: "s",
        tablerow18col: 2,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Boro",
        atomicnumber: 5,
        symbol: "B",
        category: "Metaloide",
        atomicweight: "10.81",
        atomicweightfull: "[10.806, 10.821]",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 13,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Carb&oacute;n",
        atomicnumber: 6,
        symbol: "C",
        category: "Reactivo no metal",
        atomicweight: "12.011",
        atomicweightfull: "[12.0096, 12.0116]",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 14,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Nitr&oacute;geno",
        atomicnumber: 7,
        symbol: "N",
        category: "Reactivo no metal",
        atomicweight: "14.007",
        atomicweightfull: "[14.00643, 14.00728]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 15,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Ox&oacute;geno",
        atomicnumber: 8,
        symbol: "O",
        category: "Reactivo no metal",
        atomicweight: "15.999",
        atomicweightfull: "[15.99903, 15.99977]",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 16,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Flúor",
        atomicnumber: 9,
        symbol: "F",
        category: "Reactivo no metal",
        atomicweight: "18.998",
        atomicweightfull: "18.998403163(6)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 17,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Ne&oacute;n",
        atomicnumber: 10,
        symbol: "Ne",
        category: "Gas Noble",
        atomicweight: "20.18",
        atomicweightfull: "20.1797(6)",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 2,
        block: "p",
        tablerow18col: 2,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Sodio",
        atomicnumber: 11,
        symbol: "Na",
        category: "Metal alcalino",
        atomicweight: "22.99",
        atomicweightfull: "22.98976928(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 1,
        period: 3,
        block: "s",
        tablerow18col: 3,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Magnesio",
        atomicnumber: 12,
        symbol: "Mg",
        category: "Alcalinotérreo",
        atomicweight: "24.305",
        atomicweightfull: "[24.304, 24.307] ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 2,
        period: 3,
        block: "s",
        tablerow18col: 3,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Aluminio",
        atomicnumber: 13,
        symbol: "Al",
        category: "Metal bloque p",
        atomicweight: "26.982",
        atomicweightfull: "26.9815384(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 13,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Silicio",
        atomicnumber: 14,
        symbol: "Si",
        category: "Metaloide",
        atomicweight: "28.085",
        atomicweightfull: "[28.084, 28.086] ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 14,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "F&oacute;sforo",
        atomicnumber: 15,
        symbol: "P",
        category: "Reactivo no metal",
        atomicweight: "30.974",
        atomicweightfull: "30.973761998(5) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 15,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Azúfre",
        atomicnumber: 16,
        symbol: "S",
        category: "Reactivo no metal",
        atomicweight: "32.06",
        atomicweightfull: "[32.059, 32.076] ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 16,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Cloro",
        atomicnumber: 17,
        symbol: "Cl",
        category: "Reactivo no metal",
        atomicweight: "35.45",
        atomicweightfull: "[35.446, 35.457] ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 17,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Arg&oacute;n",
        atomicnumber: 18,
        symbol: "Ar",
        category: "Gas Noble",
        atomicweight: "39.95",
        atomicweightfull: "[39.792, 39.963] ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 3,
        block: "p",
        tablerow18col: 3,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Potasio",
        atomicnumber: 19,
        symbol: "K",
        category: "Metal alcalino",
        atomicweight: "39.098",
        atomicweightfull: "39.0983(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 1,
        period: 4,
        block: "s",
        tablerow18col: 4,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Calcio",
        atomicnumber: 20,
        symbol: "Ca",
        category: "Alcalinotérreo",
        atomicweight: "40.078",
        atomicweightfull: "40.078(4) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 2,
        period: 4,
        block: "s",
        tablerow18col: 4,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Escandio",
        atomicnumber: 21,
        symbol: "Sc",
        category: "Metal en transici&oacute;n",
        atomicweight: "44.956",
        atomicweightfull: "44.955908(5) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 3,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Titanio",
        atomicnumber: 22,
        symbol: "Ti",
        category: "Metal en transici&oacute;n",
        atomicweight: "47.867",
        atomicweightfull: "47.867(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 4,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Vanadio",
        atomicnumber: 23,
        symbol: "V",
        category: "Metal en transici&oacute;n",
        atomicweight: "50.942",
        atomicweightfull: "50.9415(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 5,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Cromo",
        atomicnumber: 24,
        symbol: "Cr",
        category: "Metal en transici&oacute;n",
        atomicweight: "51.996",
        atomicweightfull: "51.9961(6) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 6,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Manganeso",
        atomicnumber: 25,
        symbol: "Mn",
        category: "Metal en transici&oacute;n",
        atomicweight: "54.938",
        atomicweightfull: "54.938043(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 7,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Hierro",
        atomicnumber: 26,
        symbol: "Fe",
        category: "Metal en transici&oacute;n",
        atomicweight: "55.845",
        atomicweightfull: "55.845(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 8,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Cobalto",
        atomicnumber: 27,
        symbol: "Co",
        category: "Metal en transici&oacute;n",
        atomicweight: "58.933",
        atomicweightfull: "58.933194(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 9,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Níquel",
        atomicnumber: 28,
        symbol: "Ni",
        category: "Metal en transici&oacute;n",
        atomicweight: "58.693",
        atomicweightfull: "58.6934(4) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 10,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Cobre",
        atomicnumber: 29,
        symbol: "Cu",
        category: "Metal en transici&oacute;n",
        atomicweight: "63.546",
        atomicweightfull: "63.546(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 11,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Zinc",
        atomicnumber: 30,
        symbol: "Zn",
        category: "Metal bloque p",
        atomicweight: "65.38",
        atomicweightfull: "65.38(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 12,
        period: 4,
        block: "d",
        tablerow18col: 4,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Galio",
        atomicnumber: 31,
        symbol: "Ga",
        category: "Metal bloque p",
        atomicweight: "69.723",
        atomicweightfull: "69.723(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 13,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Germanio",
        atomicnumber: 32,
        symbol: "Ge",
        category: "Metaloide",
        atomicweight: "72.63",
        atomicweightfull: "72.630(8) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 14,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Arsénico",
        atomicnumber: 33,
        symbol: "As",
        category: "Metaloide",
        atomicweight: "74.922",
        atomicweightfull: "74.921595(6) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 15,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Selenio",
        atomicnumber: 34,
        symbol: "Se",
        category: "Reactivo no metal",
        atomicweight: "78.971",
        atomicweightfull: "78.971(8) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 16,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Bromo",
        atomicnumber: 35,
        symbol: "Br",
        category: "Reactivo no metal",
        atomicweight: "79.904",
        atomicweightfull: "[79.901, 79.907] ",
        occurrence: "Liquid",
        stateofmatter: "Primordial",
        group: 17,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Kript&oacute;n",
        atomicnumber: 36,
        symbol: "Kr",
        category: "Gas Noble",
        atomicweight: "83.798",
        atomicweightfull: "83.798(2) ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 4,
        block: "p",
        tablerow18col: 4,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Rubidio",
        atomicnumber: 37,
        symbol: "Rb",
        category: "Metal alcalino",
        atomicweight: "85.468",
        atomicweightfull: "85.4678(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 1,
        period: 5,
        block: "s",
        tablerow18col: 5,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Estrontio",
        atomicnumber: 38,
        symbol: "Sr",
        category: "Alcalinotérreo",
        atomicweight: "87.62",
        atomicweightfull: "87.62(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 2,
        period: 5,
        block: "s",
        tablerow18col: 5,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Itrio",
        atomicnumber: 39,
        symbol: "Y",
        category: "Metal en transici&oacute;n",
        atomicweight: "88.906",
        atomicweightfull: "88.90584(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 3,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Zirconio",
        atomicnumber: 40,
        symbol: "Zr",
        category: "Metal en transici&oacute;n",
        atomicweight: "91.224",
        atomicweightfull: "91.224(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 4,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Niobio",
        atomicnumber: 41,
        symbol: "Nb",
        category: "Metal en transici&oacute;n",
        atomicweight: "92.906",
        atomicweightfull: "92.90637(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 5,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Molibdeno",
        atomicnumber: 42,
        symbol: "Mo",
        category: "Metal en transici&oacute;n",
        atomicweight: "95.95",
        atomicweightfull: "95.95(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 6,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Tecnecio",
        atomicnumber: 43,
        symbol: "Tc",
        category: "Metal en transici&oacute;n",
        atomicweight: "[97]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 7,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Rutenio",
        atomicnumber: 44,
        symbol: "Ru",
        category: "Metal en transici&oacute;n",
        atomicweight: "101.07",
        atomicweightfull: "101.07(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 8,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Rodio",
        atomicnumber: 45,
        symbol: "Rh",
        category: "Metal en transici&oacute;n",
        atomicweight: "102.91",
        atomicweightfull: "102.90549(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 9,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Paladio",
        atomicnumber: 46,
        symbol: "Pd",
        category: "Metal en transici&oacute;n",
        atomicweight: "106.42",
        atomicweightfull: "106.42(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 10,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Plata",
        atomicnumber: 47,
        symbol: "Ag",
        category: "Metal en transici&oacute;n",
        atomicweight: "107.87",
        atomicweightfull: "107.8682(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 11,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Cadmio",
        atomicnumber: 48,
        symbol: "Cd",
        category: "Metal bloque p",
        atomicweight: "112.41",
        atomicweightfull: "112.414(4) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 12,
        period: 5,
        block: "d",
        tablerow18col: 5,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Indio",
        atomicnumber: 49,
        symbol: "In",
        category: "Metal bloque p",
        atomicweight: "114.82",
        atomicweightfull: "114.818(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 13,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Estaño",
        atomicnumber: 50,
        symbol: "Sn",
        category: "Metal bloque p",
        atomicweight: "118.71",
        atomicweightfull: "118.710(7) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 14,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Antimonio",
        atomicnumber: 51,
        symbol: "Sb",
        category: "Metaloide",
        atomicweight: "121.76",
        atomicweightfull: "121.760(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 15,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Telurio",
        atomicnumber: 52,
        symbol: "Te",
        category: "Metaloide",
        atomicweight: "127.6",
        atomicweightfull: "127.60(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 16,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Yodo",
        atomicnumber: 53,
        symbol: "I",
        category: "Reactivo no metal",
        atomicweight: "126.9",
        atomicweightfull: "126.90447(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 17,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Xen&oacute;n",
        atomicnumber: 54,
        symbol: "Xe",
        category: "Gas Noble",
        atomicweight: "131.29",
        atomicweightfull: "131.293(6) ",
        occurrence: "Gas",
        stateofmatter: "Primordial",
        group: 18,
        period: 5,
        block: "p",
        tablerow18col: 5,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Cesio",
        atomicnumber: 55,
        symbol: "Cs",
        category: "Metal alcalino",
        atomicweight: "132.91",
        atomicweightfull: "132.90545196(6) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 1,
        period: 6,
        block: "s",
        tablerow18col: 6,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Bario",
        atomicnumber: 56,
        symbol: "Ba",
        category: "Alcalinotérreo",
        atomicweight: "137.33",
        atomicweightfull: "137.327(7) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 2,
        period: 6,
        block: "s",
        tablerow18col: 6,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Lantano",
        atomicnumber: 57,
        symbol: "La",
        category: "Lantánido",
        atomicweight: "138.91",
        atomicweightfull: "138.90547(7) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 3,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Cerio",
        atomicnumber: 58,
        symbol: "Ce",
        category: "Lantánido",
        atomicweight: "140.12",
        atomicweightfull: "140.116(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Praseodimio",
        atomicnumber: 59,
        symbol: "Pr",
        category: "Lantánido",
        atomicweight: "140.91",
        atomicweightfull: "140.90766(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Neodimio",
        atomicnumber: 60,
        symbol: "Nd",
        category: "Lantánido",
        atomicweight: "144.24",
        atomicweightfull: "144.242(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Prometio",
        atomicnumber: 61,
        symbol: "Pm",
        category: "Lantánido",
        atomicweight: "[145]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Samario",
        atomicnumber: 62,
        symbol: "Sm",
        category: "Lantánido",
        atomicweight: "150.36",
        atomicweightfull: "150.36(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Europio",
        atomicnumber: 63,
        symbol: "Eu",
        category: "Lantánido",
        atomicweight: "151.96",
        atomicweightfull: "151.964(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Gadolinio",
        atomicnumber: 64,
        symbol: "Gd",
        category: "Lantánido",
        atomicweight: "157.25",
        atomicweightfull: "157.25(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Terbio",
        atomicnumber: 65,
        symbol: "Tb",
        category: "Lantánido",
        atomicweight: "158.93",
        atomicweightfull: "158.925354(8) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Disprosio",
        atomicnumber: 66,
        symbol: "Dy",
        category: "Lantánido",
        atomicweight: "162.5",
        atomicweightfull: "162.500(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Holmio",
        atomicnumber: 67,
        symbol: "Ho",
        category: "Lantánido",
        atomicweight: "164.93",
        atomicweightfull: "164.930328(7) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Erbio",
        atomicnumber: 68,
        symbol: "Er",
        category: "Lantánido",
        atomicweight: "167.26",
        atomicweightfull: "167.259(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Tulio",
        atomicnumber: 69,
        symbol: "Tm",
        category: "Lantánido",
        atomicweight: "168.93",
        atomicweightfull: "168.934218(6) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Iterbio",
        atomicnumber: 70,
        symbol: "Yb",
        category: "Lantánido",
        atomicweight: "173.05",
        atomicweightfull: "173.045(10) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Lutecio",
        atomicnumber: 71,
        symbol: "Lu",
        category: "Lantánido",
        atomicweight: "174.97",
        atomicweightfull: "174.9668(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 6,
        block: "f",
        tablerow18col: 8,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Hafnio",
        atomicnumber: 72,
        symbol: "Hf",
        category: "Metal en transici&oacute;n",
        atomicweight: "178.49",
        atomicweightfull: "178.49(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 4,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Tantalo",
        atomicnumber: 73,
        symbol: "Ta",
        category: "Metal en transici&oacute;n",
        atomicweight: "180.95",
        atomicweightfull: "180.94788(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 5,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Wolframio",
        atomicnumber: 74,
        symbol: "W",
        category: "Metal en transici&oacute;n",
        atomicweight: "183.84",
        atomicweightfull: "183.84(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 6,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Renio",
        atomicnumber: 75,
        symbol: "Re",
        category: "Metal en transici&oacute;n",
        atomicweight: "186.21",
        atomicweightfull: "186.207(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 7,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Osmio",
        atomicnumber: 76,
        symbol: "Os",
        category: "Metal en transici&oacute;n",
        atomicweight: "190.23",
        atomicweightfull: "190.23(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 8,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Iridio",
        atomicnumber: 77,
        symbol: "Ir",
        category: "Metal en transici&oacute;n",
        atomicweight: "192.22",
        atomicweightfull: "192.217(2) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 9,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Platino",
        atomicnumber: 78,
        symbol: "Pt",
        category: "Metal en transici&oacute;n",
        atomicweight: "195.08",
        atomicweightfull: "195.084(9) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 10,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Oro",
        atomicnumber: 79,
        symbol: "Au",
        category: "Metal en transici&oacute;n",
        atomicweight: "196.97",
        atomicweightfull: "196.966570(4) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 11,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Mercurio",
        atomicnumber: 80,
        symbol: "Hg",
        category: "Metal bloque p",
        atomicweight: "200.59",
        atomicweightfull: "200.592(3) ",
        occurrence: "Liquid",
        stateofmatter: "Primordial",
        group: 12,
        period: 6,
        block: "d",
        tablerow18col: 6,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Talio",
        atomicnumber: 81,
        symbol: "Tl",
        category: "Metal bloque p",
        atomicweight: "204.38",
        atomicweightfull: "[204.382, 204.385] ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 13,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Plomo",
        atomicnumber: 82,
        symbol: "Pb",
        category: "Metal bloque p",
        atomicweight: "207.2",
        atomicweightfull: "207.2(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 14,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Bismuto",
        atomicnumber: 83,
        symbol: "Bi",
        category: "Metal bloque p",
        atomicweight: "208.98",
        atomicweightfull: "208.98040(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 15,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Polonio",
        atomicnumber: 84,
        symbol: "Po",
        category: "Metal bloque p",
        atomicweight: "[209]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 16,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Astato",
        atomicnumber: 85,
        symbol: "At",
        category: "Metaloide",
        atomicweight: "[210]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 17,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Rad&oacute;n",
        atomicnumber: 86,
        symbol: "Rn",
        category: "Gas Noble",
        atomicweight: "[222]",
        atomicweightfull: "-",
        occurrence: "Gas",
        stateofmatter: "Descomposici&oacute;n",
        group: 18,
        period: 6,
        block: "p",
        tablerow18col: 6,
        tablecolumn18col: 18,
        visible: true
    },
    {
        name: "Francio",
        atomicnumber: 87,
        symbol: "Fr",
        category: "Metal alcalino",
        atomicweight: "[223]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 1,
        period: 7,
        block: "s",
        tablerow18col: 7,
        tablecolumn18col: 1,
        visible: true
    },
    {
        name: "Radio",
        atomicnumber: 88,
        symbol: "Ra",
        category: "Alcalinotérreo",
        atomicweight: "[226]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 2,
        period: 7,
        block: "s",
        tablerow18col: 7,
        tablecolumn18col: 2,
        visible: true
    },
    {
        name: "Actinio",
        atomicnumber: 89,
        symbol: "Ac",
        category: "Actínido",
        atomicweight: "[227]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 3,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 3,
        visible: true
    },
    {
        name: "Torio",
        atomicnumber: 90,
        symbol: "Th",
        category: "Actínido",
        atomicweight: "232.04",
        atomicweightfull: "232.0377(4) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Protactinio",
        atomicnumber: 91,
        symbol: "Pa",
        category: "Actínido",
        atomicweight: "231.04",
        atomicweightfull: "231.03588(1) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Uranio",
        atomicnumber: 92,
        symbol: "U",
        category: "Actínido",
        atomicweight: "238.03",
        atomicweightfull: "238.02891(3) ",
        occurrence: "S&oacute;lido",
        stateofmatter: "Primordial",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Neptunio",
        atomicnumber: 93,
        symbol: "Np",
        category: "Actínido",
        atomicweight: "[237]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Plutonio",
        atomicnumber: 94,
        symbol: "Pu",
        category: "Actínido",
        atomicweight: "[244]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Descomposici&oacute;n",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Americio",
        atomicnumber: 95,
        symbol: "Am",
        category: "Actínido",
        atomicweight: "[243]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Curio",
        atomicnumber: 96,
        symbol: "Cm",
        category: "Actínido",
        atomicweight: "[247]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Berkelio",
        atomicnumber: 97,
        symbol: "Bk",
        category: "Actínido",
        atomicweight: "[247]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Californio",
        atomicnumber: 98,
        symbol: "Cf",
        category: "Actínido",
        atomicweight: "[251]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Einsteinio",
        atomicnumber: 99,
        symbol: "Es",
        category: "Actínido",
        atomicweight: "[252]",
        atomicweightfull: "-",
        occurrence: "S&oacute;lido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Fermio",
        atomicnumber: 100,
        symbol: "Fm",
        category: "Actínido",
        atomicweight: "[257]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Mendelevio",
        atomicnumber: 101,
        symbol: "Md",
        category: "Actínido",
        atomicweight: "[258]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Nobelio",
        atomicnumber: 102,
        symbol: "No",
        category: "Actínido",
        atomicweight: "[259]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Laurencio",
        atomicnumber: 103,
        symbol: "Lr",
        category: "Actínido",
        atomicweight: "[266]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 0,
        period: 7,
        block: "f",
        tablerow18col: 9,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Rutherfordio",
        atomicnumber: 104,
        symbol: "Rf",
        category: "Metal en transici&oacute;n",
        atomicweight: "[267]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 4,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 4,
        visible: true
    },
    {
        name: "Dubnio",
        atomicnumber: 105,
        symbol: "Db",
        category: "Metal en transici&oacute;n",
        atomicweight: "[268]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 5,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 5,
        visible: true
    },
    {
        name: "Seaborgio",
        atomicnumber: 106,
        symbol: "Sg",
        category: "Metal en transici&oacute;n",
        atomicweight: "[269]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 6,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 6,
        visible: true
    },
    {
        name: "Bohrio",
        atomicnumber: 107,
        symbol: "Bh",
        category: "Metal en transici&oacute;n",
        atomicweight: "[270]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 7,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 7,
        visible: true
    },
    {
        name: "Hassio",
        atomicnumber: 108,
        symbol: "Hs",
        category: "Metal en transici&oacute;n",
        atomicweight: "[269]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 8,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 8,
        visible: true
    },
    {
        name: "Meitnerio",
        atomicnumber: 109,
        symbol: "Mt",
        category: "Desconocido",
        atomicweight: "[278]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 9,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 9,
        visible: true
    },
    {
        name: "Darmstatio",
        atomicnumber: 110,
        symbol: "Ds",
        category: "Desconocido",
        atomicweight: "[281]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 10,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 10,
        visible: true
    },
    {
        name: "Roentgenio",
        atomicnumber: 111,
        symbol: "Rg",
        category: "Desconocido",
        atomicweight: "[282]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 11,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 11,
        visible: true
    },
    {
        name: "Copernico",
        atomicnumber: 112,
        symbol: "Cn",
        category: "Metal bloque p",
        atomicweight: "[285]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 12,
        period: 7,
        block: "d",
        tablerow18col: 7,
        tablecolumn18col: 12,
        visible: true
    },
    {
        name: "Nihonio",
        atomicnumber: 113,
        symbol: "Nh",
        category: "Desconocido",
        atomicweight: "[286]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 13,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 13,
        visible: true
    },
    {
        name: "Flerovio",
        atomicnumber: 114,
        symbol: "Fl",
        category: "Desconocido",
        atomicweight: "[289]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 14,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 14,
        visible: true
    },
    {
        name: "Moscovio",
        atomicnumber: 115,
        symbol: "Mc",
        category: "Desconocido",
        atomicweight: "[290]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 15,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 15,
        visible: true
    },
    {
        name: "Livermorio",
        atomicnumber: 116,
        symbol: "Lv",
        category: "Desconocido",
        atomicweight: "[293]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 16,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 16,
        visible: true
    },
    {
        name: "Teneso",
        atomicnumber: 117,
        symbol: "Ts",
        category: "Desconocido",
        atomicweight: "[294]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 17,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 17,
        visible: true
    },
    {
        name: "Oganes&oacute;n",
        atomicnumber: 118,
        symbol: "Og",
        category: "Desconocido",
        atomicweight: "[294]",
        atomicweightfull: "-",
        occurrence: "Desconocido",
        stateofmatter: "Sintético",
        group: 18,
        period: 7,
        block: "p",
        tablerow18col: 7,
        tablecolumn18col: 18,
        visible: true
    },
]
